language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly


matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-musl BIN_NAME=genact
      os: linux
    - env: TARGET=x86_64-pc-windows-gnu BIN_NAME=genact.exe
      os: linux
    - env: TARGET=x86_64-apple-darwin BIN_NAME=genact
      os: osx

  os:
    - linux
    - osx

before_install:
  - rustup self update

install:
  - if [[ -n $TARGET && $TARGET != "x86_64-apple-darwin" ]]; then rustup target add $TARGET; fi

script:
  - if [[ -n $TARGET ]]; then cargo build --verbose --release --target $TARGET; else cargo build --verbose; fi

deploy:
  provider: releases
  api_key:
    secure: "n1OCiCjupkVieqsepGBOk6oxGcU89n9z0lQWWMAtBKREIEL1fnqt7A4z9FC1LV9UiAwvcvMHI8As5TA/7sV6jiWFuNOqu5HurX/n7cXlAuVWx00gCtWZ7Fh14ipVIDr2W52Mj/5qw1LSW19g8+9nLF1xO2YLrNpiaQX+V6Ypf04="
  file: target/$TARGET/release/$BIN_NAME
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_RUST_VERSION = stable
    condition: -n $TARGET
