[package]
name = "genact"
description = "A nonsense activity generator"
version = "0.1.1"
repository = "https://github.com/svenstaro/genact"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
pbr = "*"
yansi = "0.3"
rand = "0.4"
chrono = "0.4"

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
clap = "2.29"

[target.'cfg(target_os = "emscripten")'.dependencies]
emscripten-sys = "0.3"

[profile.release]
lto = true
